### ISSUE TITLE
Create Testcases for User Stories in Sprint 2

### ISSUE THREAD

**Issue by vsw229** [nyu-devops-spring-2019/wishlists#24]
**As a** developer
**I need** to be able to easily test what I have built
**So that** I know my code is working

**Assumptions:**
Every user story needs a separate test case

**Acceptance Criteria**
...

Given a test case was build
When testing
Then it becomes clear whether it works

**Comment by vsw229** [comment]
Guys, please advise me how many test case we need in sprint 2 and how best to split that up in user stories

**Comment by NavitaGaur** [comment]
We can create this as an epic. I also saw other zenhubs and they have separate issues of testing for every method that they are creating
