### ISSUE TITLE
Create a Cloud Foundry application in IBM Cloud

### ISSUE THREAD

**Issue by vsw229** [nyu-devops-spring-2019/wishlists#80]
**As a** developer
**I need** to create a Cloud Foundry app
**So that** I can deploy to the Cloud

**Assumptions:**
All developers need to do this. WATCH NAMING! SEE COMMENT BELOW

**Acceptance Criteria**
Given that we have access to the IBMbluemix cloud
When we create a python web server app using Flask and deploy it
Then the applications runs on the cloud

**Comment by vsw229** [comment]
From HW: Create a Cloud Foundry application in IBM Cloud
Naming is very important because it becomes your URL so please follow the following format:
Use the singular version of your resource name (e.g., orders becomes order)
prefixed by nyu- and suffixed by -service-s19.
For example: if you are creating the /orders API then please name your IBM Cloud microservice nyu-order-service-s19 (The full URL will then be nyu-order-service-s19.mybluemix.net )

**Comment by NavitaGaur** [comment]
Acceptance Criteria

Given that we have access to the IBMbluemix cloud 
When we create a python web server app using Flask and deploy it
Then the applications runs on the cloud
