### ISSUE TITLE
Create a database service for your Cloud Foundry app and bind to app

### ISSUE THREAD

**Issue by vsw229** [nyu-devops-spring-2019/wishlists#81]
**As a** developer
**I need** to create a data base service
**So that** I can deploy to the Cloud

**Assumptions:**
...

**Acceptance Criteria**
...

Given ...
When ...
Then ...

**Comment by vsw229** [comment]
From HW: Create a database service for your Cloud Foundry app
Bind the database service to the Cloud Foundry app

**Comment by NavitaGaur** [comment]
Hey Celine,

Are you working on this? I created the cloudant database and binded our app with it. Is there anything else that was supposed to be done?
