### ISSUE TITLE
Push app to IBM Cloud

### ISSUE THREAD

**Issue by vsw229** [nyu-devops-spring-2019/wishlists#84]
**As a** developer
**I need** to push my application to the IBM Cloud
**So that** I can deploy to the Cloud

Assumptions: All the code in github is working

Acceptance Criteria:
Given that our code is working
When we click on the URL
Then the app is running on the URL https://nyu-wishlist-service-s19.mybluemix.net/

**Comment by vsw229** [comment]
From HW: Use cf push to push your application to IBM Cloud (Bluemix)
Go to the URL of your service and make sure that it works

**Comment by NavitaGaur** [comment]
Assumptions: All the code in github is working

Acceptance Criteria:
Given that our code is working
When we click on the URL
Then the app is running on the URL https://nyu-wishlist-service-s19.mybluemix.net/
